README.md
Reversed the order of Payara server versions in the overview page
=> Version 162: Reversed the order of Payara server versions

README.md, build-instructions/build-instructions.md, general-info/general-info.md
Reverts payara/Payara-Server-Documentation#8
=> Revert "changed logo on build instructions and general info pages - 162"

release-notes/release-notes-162.md
=> 162 release note branch

documentation/payara-micro/payara-micro.md
Contents
Update payara-micro.md
Formatting
=> PAYARA-654

SUMMARY.md, documentation/extended-documentation/system-properties.md
=> PAYARA-653

documentation/payara-micro/payara-micro.md
- Missing "" for String path.
- Changed introduction to Uber-Jar
=> Corrected Java Example

documentation/extended-documentation/classloading.md, documentation/extended-documentation/system-properties.md
=> PAYARA-790 ClassLoading documentation

book.json, documentation/extended-documentation/advanced-jdbc/slow-sql-logger.md, documentation/extended-documentation/health-check-service/health-check-service.md
Minor improvements according to suggestions.
=> Fixes for discussions in gitbook

SUMMARY.md, release-notes/release-notes-history.md
Fixes #54 
Adds appendix for release notes, also introduces sections: General Info, Technical Documentation, Appendices
Preview at https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/next_release_notes/release-notes/release-notes-history.html
=> Release notes appendix

styles/website.css
More compact menu, smaller spaces, bold font for main sections, selected page with black background.
Preview here: https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/customcss/
=> Improved styling of menu in the sidebar

documentation/extended-documentation/notification-service/notification-service.md, documentation/extended-documentation/request-tracing-service/request-tracing-service.md
PYSVC-123 - Added docs about notification service enabled by default (preview [here](https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/130e9567eed24444eb110480d15760fbaaba14aa/documentation/extended-documentation/notification-service/notification-service.html))
Added docs to request tracing. List of events and requests traced (preview [here](https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/130e9567eed24444eb110480d15760fbaaba14aa/documentation/extended-documentation/request-tracing-service/request-tracing-service.html))
=> 164 new features - notification and request tracing

documentation/payara-micro/appendices/cmd-line-opts.md
=> Added the deployDir alias to the same row as deploymentDir

documentation/payara-micro/maven/maven.md
https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/0bc1e12a380faa628825dd85eeda0ad89457a0a0/documentation/payara-micro/maven/maven.html
Fixes the version variable in #98
=> Fixed the version variable in #98

reference-information.md
- Removed reference-information.md
Auto commit by GitBook Editor
=> Removed redundant file

SUMMARY.md, build-instructions/build-instructions.md, documentation/extended-documentation/jcache.md, general-info/general-info.md
Refactored the _General Information_ and _Build Instructions_ page articles to use the **TOC** convention. Also made some adjustments to the General Information page to keep it up to date.
=> Minor refactoring on introduction articles

documentation/extended-documentation/asadmin-recorder.md
Fixes  https://www.gitbook.com/book/payara/payara-server/discussions/15
Cherry pick of #102 to the `next` branch.
=> 171 fix asadmin recorder

security.md
=> Updates security.md

documentation/payara-micro/appendices/cmd-line-opts.md
Just added a sentence to say that from 171, there is case insensitivity, but there are new commands which need adding to the list which I will do in this PR
=> PYSVC-253 case insensitivity // PYSVC-322 document all Payara Micro command line options

documentation/payara-micro/stopping/stopping.md
=> PYSVC-186 Added CTRL-C as a way to shut down Micro Instances

documentation/extended-documentation/classloading.md, documentation/payara-micro/callable-objects.md, documentation/payara-micro/configuring/package-uberjar.md
- Documented new functionality on packaging additional files on Uber JARs created using Payara Micro.
- Minor fixes on Payara Micro documentation articles
=> PYSVC 249  - Packaging additional files into Uber JAR

SUMMARY.md
Changed the line with phonehome-overview
=> Fixed a broken link

.gitattributes
To avoid diff in github reporting changes for lines that were not changed.
=> Adding git attributes file to force CRLF line endings.

documentation/core-documentation/jacc.adoc, documentation/core-documentation/javamail.adoc, documentation/core-documentation/rest-api/definitions.adoc, documentation/core-documentation/rest-api/overview.adoc, documentation/core-documentation/rest-api/resources.adoc, documentation/core-documentation/rest-api/security.adoc
Preview: https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/c4466b76222e18739c7ea9e63dff25802231d403/
=> Core section fixes after migration to adoc PYSVC-372

documentation/core-documentation/core-documentation.adoc
To point to the new site at github
=> Updated the link to GlassFish OS docs

documentation/extended-documentation/system-properties.adoc
=> PAYARA-1719 Document Grizzly System Property

documentation/extended-documentation/asadmin-commands/asadmin-commands.adoc
Implemented documentation for new domain manipulation commands on 173, refactored structure of page article
=> Documented plural lifecycle commands introduced on 173

SUMMARY.adoc, release-notes/release-notes-173.adoc
Preview: http://docs.payara.fish/v/173_version/
=> 173 version

documentation/extended-documentation/jbatch/asadmin.adoc
Implemented issue `PAYARA-1880`. Updates for the _asadmin_ documentation article for JBatch
=> Improved documentation for asadmin commands for JBatch API

documentation/extended-documentation/app-deployment/deployment-descriptors.adoc, documentation/extended-documentation/app-deployment/descriptor-elements.adoc
Implemented documentation changes for the new feature on 4.1.2.173 [PAYARA-1752], default login configuration for EJB web services.
=> Payara 1752

documentation/core-documentation/rest-api/definitions.adoc, documentation/core-documentation/rest-api/rest-api-documentation.adoc, documentation/core-documentation/rest-api/security.adoc, documentation/extended-documentation/phone-home/phone-home-information.adoc, documentation/payara-micro/appendices/operation-methods.adoc, release-notes/release-notes-161.adoc
Fixed some links for the current version 173
Preview: https://docs.payara.fish/v/173-fix-broken-links/
=> 173 fix broken links

documentation/extended-documentation/hazelcast/configuration.adoc
=> PYSVC-504 document that payaara uses its own serialiser

documentation/core-documentation/server-configuration/var-substitution/usage-of-variables.adoc
https://mattgill98.gitbooks.io/payara-server-documentation/v/payara-1744-document-post-boot-commands-environment-variables/documentation/core-documentation/configuration/var-substitution/usage-of-variables.html
=> PAYARA-1744 documented environment variables in post boot command files

documentation/user-guides/restore-domain.adoc
Small change to the restore domain guide
=> Small fix to restore domain guide

SUMMARY.adoc, documentation/extended-documentation/advanced-jdbc/advanced-monitoring-stats.adoc
Documented advanced JDBC monitoring stats for frequently used SQL queries and slowest SQL queries.
=> [PAYARA-1606] Advanced JDBC monitoring stats for SQL queries

security/security-fix-list.adoc
Minor changes to segregate listed non-CVE vulnerabilities in the security fix list.
=> Security List Changes

documentation/core-documentation/asadmin-commands/misc-commands.adoc, documentation/core-documentation/asadmin-commands/server-management-commands.adoc, documentation/extended-documentation/hazelcast/asadmin.adoc, documentation/extended-documentation/jmx-monitoring-service/asadmin-commands.adoc, documentation/extended-documentation/jmx-monitoring-service/jmx-notification-configuration.adoc, documentation/extended-documentation/request-tracing-service/asadmin-commands.adoc, documentation/user-guides/backup-domain.adoc, documentation/user-guides/monitoring/mbeans.adoc
Please review and approve/merge so that we can finally update the 174 docs.
=> Fixes according to comments in PR #273

SUMMARY.adoc
Quick fix to ToC for broken link
=> Quick fix to MBeans monitoring documentation

SUMMARY.adoc
Writing JMX Blog, couldn't link to it.
=> PYSVC-632 Fix MBeans Link

documentation/extended-documentation/ejb.adoc
Bringing last updates to 174 documentation release from master.
=> Udpate to 174 docs

documentation/extended-documentation/ejb.adoc
Improvements on enhanced EJB documentation article.
=> Improvements on EJB configuration/deploment

documentation/extended-documentation/cdi-events.adoc
CDI event bus added to Web version with PAYARA-1445
=> Fixes since when CDI event bus is available

documentation/extended-documentation/ejb.adoc
Documented the EJB Timer Store. The Admin Console / Asadmin integration does not appear to be finished according to the GitHub issue so I've documented the direct domain.xml edit.
=> PYSVC-91 Document the Hazelcast EJB Timer Store

SUMMARY.adoc, book.json, documentation/microprofile/metrics.adoc
Will probably need a rebase/conflict fix for the summary due to how close the other MP docs will be
=> PYSVC-639 MicroProfile Metrics

documentation/microprofile/config.adoc
Document standard Payara config properties available with the Microprofile configuration api
=> PYSVC-683 Add standard configuration properties

documentation/microprofile/README.adoc
Leave open for a while for future fixes
=> Batch fix PR for 4.181

SUMMARY.adoc, documentation/microprofile/README.adoc, documentation/microprofile/jwt.adoc, documentation/payara-server/app-deployment/deployment-descriptors.adoc, documentation/payara-server/app-deployment/descriptor-elements.adoc
=> PAYARA-2460 Initial documentation for MP JWT-Auth

security/security-fix-list.adoc
Updated security page regarding fix for CORBA security issue.
=> PAYARA-2656 Update Security Fixes

SUMMARY.adoc
An old, dead link for Virtual Servers had been left behind
=> Remove dead link

general-info/general-info.adoc, security/security-fix-list.adoc
Synchronize changes from the released docs
=> Sync from 5.181

book.json, documentation/microprofile/metrics.adoc
=> Increase MP Metrics version variable

SUMMARY.adoc, documentation/user-guides/using-the-maven-cargo-plugin.adoc
Redid #288 with requested changes. There may still be improvements that could be made, but I would suggest this be merged and fixed afterwards, since the old PR got stale quickly due to the SUMMARY.adoc changing.
=> PYSVC-75 Convert the Maven Cargo Plugin Blog to a User Guide

book.json, documentation/microprofile/config.adoc
=> Update MP Config to 1.2

SUMMARY.adoc, book.json, documentation/microprofile/openapi.adoc
https://mattgill98.gitbooks.io/payara-server-documentation/content/v/14524b2c3b3c5223b9f41dc4233cb73dd3ffe05e/documentation/microprofile/openapi.html
=> PAYARA-2648 Document OpenAPI

documentation/payara-server/README.adoc
https://mattgill98.gitbooks.io/payara-server-documentation/content/v/PYSVC-839-Incorrect-GlassFish-Documentation-Link/documentation/payara-server/
=> PYSVC-839 Incorrect GlassFish Documentation Link

SUMMARY.adoc, schemas/README.adoc, schemas/payara-web-app_4.dtd
For https://github.com/payara/Payara/pull/2964
=> PAYARA-2968 Add payara-web-app_4.dtd

SUMMARY.adoc, schemas/README.adoc, schemas/payara-web-app_4.dtd
PAYARA-2968 Add payara-web-app_4.dtd
=> PAYARA-2968 Add payara-web-app_4.dtd - Payara4

documentation/microprofile/faulttolerance.adoc
In combo with https://github.com/payara/Payara-Server-Documentation/pull/411, which contains updates to the book.json and readme files.
=> PAYARA-2989 Fault Tolerance 1.1

SUMMARY.adoc, book.json, documentation/payara-server/app-deployment/deployment-descriptors.adoc, documentation/payara-server/app-deployment/descriptor-elements.adoc, schemas/README.adoc
Link to payara web dtd was breaking gitbook build, changed to raw URL
=> Edit of payara web descriptor info.

SUMMARY.adoc, documentation/payara-server/server-configuration/http/network-listeners.adoc, documentation/payara-server/server-configuration/http/protocols.adoc, documentation/payara-server/server-configuration/http/protocols/protocols-asadmin.adoc, documentation/payara-server/server-configuration/http/virtual-servers.adoc
=> Added TOC to long pages

documentation/payara-micro/asadmin/send-asadmin-commands.adoc
(cherry picked from commit a06dfbc68ab53f577b5a90eefcbe26f14876b015)
=> PAYARA-3326 Edit title and a couple other minor adjustments

release-notes/release-notes-184.adoc
Adds details about upgrading and moves notes to the beginning
=> Update 184 release notes about upgrading

documentation/user-guides/using-the-maven-cargo-plugin.adoc
=> Update link in cargo plugin documentation

SUMMARY.adoc, release-notes/release-notes-4-182.adoc, release-notes/release-notes-4-183.adoc, release-notes/release-notes-4-184.adoc
=> Release notes for customer versions of Payara 4 PYSVC-1003

documentation/payara-micro/appendices/cmd-line-opts.adoc, documentation/payara-server/system-properties.adoc
Documentation for https://github.com/payara/Payara/pull/3702
=> PAYARA-3475 Added Rows on shutdowngrace System Property and Command Option

documentation/payara-server/hazelcast/configuration.adoc
Added documentation for the setting added by https://payara.atlassian.net/browse/PAYARA-3457
=> PAYARA-3491 Added row on port auto increment

documentation/payara-server/system-properties.adoc
Documentation on https://github.com/payara/Payara/pull/3747
=> PAYARA-3498 Added row for new system property to restrict FORM based auth

documentation/payara-server/asadmin-commands/disabling-jline.adoc, documentation/payara-server/system-properties.adoc
Added a new system-properties entry for the JLine logging disable feature when using asadmin multimode
=> PAYARA-3531 Updated system-properties.adoc

documentation/payara-server/ejb.adoc
=> PAYARA-3525 PAYARA-3526 Document new EJB remote HTTP feature

documentation/payara-micro/appendices/cmd-line-opts.adoc, documentation/payara-micro/deploying/deploy-cmd-line.adoc
Documentation for new Payara Micro command line option added by https://github.com/payara/Payara/pull/3682.
=> PAYARA-1599 Context root cmd line options

SUMMARY.adoc
to point to 191 instead of 184
=> Fixed release notes version

documentation/payara-server/asadmin-commands/asadmin-commands.adoc
Link was missing to this page so I just added one
=> PAYARA-3664 Added link to JLine logging page

documentation/payara-server/asadmin-commands/server-management-commands.adoc
PAYARA-3688
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
=> PAYARA-3688 Added doc for start-local-instance and timeout option

documentation/payara-server/ejb/lite-remote-ejb.adoc
Also document current limitations of ejb lite connector.
=> PAYARA-3654: Document client side adapters

documentation/microprofile/metrics.adoc
Updating the MicroProfile Metrics custom vendor templating feature documentation on older release 5.184
=> Clarifications to MP Metrics custom vendor docs

documentation/payara-server/docker/docker-nodes.adoc
Add additional documentation about setting up your environment for Docker Nodes
=> PAYARA-3955 Additional Docker Nodes Documentation

documentation/payara-micro/services/request-tracing.adoc, documentation/payara-server/request-tracing-service/configuration.adoc, documentation/payara-server/request-tracing-service/terminology.adoc, documentation/payara-server/request-tracing-service/usage.adoc
Address Review comments made on https://github.com/payara/Payara-Server-Documentation/pull/561
=> PAYARA-3986 Request Tracing Documentation Update

SUMMARY.adoc, documentation/payara-micro/services/request-tracing.adoc, documentation/payara-server/notification-service/asadmin-commands.adoc, documentation/payara-server/request-tracing-service/configuration.adoc, documentation/payara-server/request-tracing-service/request-tracing-service.adoc, documentation/payara-server/request-tracing-service/terminology.adoc, documentation/payara-server/request-tracing-service/usage.adoc
PAYARA-3986 PAYARA-4009 Update Request Tracing Documentation and Correct Command Documentation
=> PAYARA-3986 Update Request Tracing Documentation - 5.192

SUMMARY.adoc, documentation/payara-micro/services/request-tracing.adoc, documentation/payara-server/notification-service/asadmin-commands.adoc, documentation/payara-server/request-tracing-service/configuration.adoc, documentation/payara-server/request-tracing-service/request-tracing-service.adoc, documentation/payara-server/request-tracing-service/terminology.adoc, documentation/payara-server/request-tracing-service/usage.adoc
PAYARA-3986 PAYARA-4009 Update Request Tracing Documentation and Correct Command Documentation
=> PAYARA-3986 Update Request Tracing Documententation - 5.191

SUMMARY.adoc, documentation/payara-server/asadmin-commands/auto-naming.adoc
Documentation for https://github.com/payara/Payara/pull/4090
=> PAYARA-3573 Document Auto-Naming

documentation/payara-server/docker/docker-instances.adoc
Changes brought in to allow for autonaming.
=> PAYARA-3988 Document changes to docker instances

documentation/payara-server/monitoring-console/monitoring-console.adoc
PR adds a page on the state of monitoring console.
=> PAYARA-4075 Summary page for Monitoring Console

book.json
Followed the description here: https://github.com/GitbookIO/plugin-versions/pull/6/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
My intention is to cherry-pick the first commit to every publicly accessible branch
=> Fix config branch book.json

book.json
This reverts commit 2425e85ce3724f5aad71393709702b5ea6df0aa7, reversing
changes made to 4cac5ebea42ef9a55c9aef3258088f34c1617604.
=> Revert "Merge pull request #615 from MattGill98/5.181"

book.json
This reverts commit a5a7e4bbc6f11278b6b0aa7f7102516775ecfbbf, reversing
changes made to 5c469134194bd73eb1495a8943b1af209d8923ef.
=> Revert "Merge pull request #616 from MattGill98/181"

book.json
This reverts commit 90c38401e54ab28605752e60252b293e44baa760, reversing
changes made to c3a087ec48144cbc79ba781d7778f30f6c3ed4ef.
=> Revert "Merge pull request #617 from MattGill98/174"

SUMMARY.adoc, jakartaee-certification/5.193/README.adoc, jakartaee-certification/5.193/tck-results-full-5.193.1.adoc, jakartaee-certification/README.adoc
This adds section for publishing TCK test results.
Actual test outputs are commented out at this point, we can compare and uncomment them as CI jobs will complete.
=> PAYARA-4142: Prepare TCK results documentation section

SUMMARY.adoc, jakartaee-certification/5.193/README.adoc, jakartaee-certification/5.193/tck-results-full-5.193.1.adoc, jakartaee-certification/README.adoc
To make the changes live they need to be included on the branch currently marked as latest.
=> TCK report for branch 5.193

SUMMARY.adoc, release-notes/README.adoc, release-notes/release-notes-193.adoc
5.193.1 notes being added in to 5.193 branch
=> 5.193 branch docs updates

SUMMARY.adoc, release-notes/README.adoc, release-notes/release-notes-193.adoc
It's been decided that the new release notes will be added in with the 5.193 release notes as opposed to creating a new branch of documentation for the 5.193.1 release, thus this PR will be made into 5.193 and master branch containing a merge of the 5.193 and 5.193.1 release notes
=> 5.193 master branch docs update

documentation/payara-server/app-deployment/app-deployment.adoc
=> Fix of #634 - formatting typo

documentation/payara-server/deployment-groups/asadmin-commands.adoc
PAYARA-4027 Add timeout parameter to start-deployment-group command
=> PAYARA-4027 maint

documentation/microprofile/opentracing.adoc
Comments made here: https://github.com/payara/Payara-Server-Documentation/pull/622
=> Address Fabio's comments

documentation/microprofile/openapi.adoc
Maintenance PR of https://github.com/payara/Payara-Server-Documentation/pull/639
=> PAYARA-4233 Document CORS headers 5.193

documentation/microprofile/openapi.adoc
Maintenance PR of https://github.com/payara/Payara-Server-Documentation/pull/639
=> PAYARA-4233 Document CORS headers 5.192

documentation/payara-server/public-api/roles-permitted.adoc
Added more clarification to the new `@RolesPermitted` annotation capabilities added in 5.193
=> Small changes to roles-pemitted docs in 5.193

documentation/payara-server/public-api/roles-permitted.adoc
Added more clarification to the new `@RolesPermitted` annotation capabilities added in 5.193
=> Small changes to roles-pemitted docs in 5.193 (to master)

SUMMARY.adoc, jakartaee-certification/5.194/README.adoc, jakartaee-certification/5.194/tck-results-full-5.194.adoc
Based on last night's run against RC3.
Best way is to check is to compare to previous test results (and they are the same), just the timed tests (cdi and beanvalidation) were a little bit faster this time.
=> Jakarta TCK Summary for Payara Server 5.194

SUMMARY.adoc, documentation/ecosystem/maven-bom.adoc
In addition to general information lists (IMO) common dependency snippets to copy-paste to users's projects.
Example project that it refers to is not merged yet, waits for final release of 5.194. You can see it at https://github.com/payara/Payara-Examples/pull/115
=> PAYARA-3924: Documentation on Payara BOM

documentation/user-guides/monitoring/monitoring-console.adoc
Documentation for PR https://github.com/payara/Payara/pull/4361
=> Added documentation on MC color configuration options

documentation/payara-server/public-api/realm-identitystores/README.adoc, documentation/payara-server/public-api/realm-identitystores/file-identity-store-definition.adoc, documentation/payara-server/public-api/realm-identitystores/pam-identity-store-definition.adoc, documentation/payara-server/public-api/realm-identitystores/realm-identity-store-definition.adoc, documentation/payara-server/public-api/realm-identitystores/solaris-identity-store-definition.adoc
Signed-off-by: Gaurav Gupta <gaurav.gupta.jc@gmail.com>
=> PAYARA-2598 Documentation update for Payara Realms Identity Stores

documentation/payara-server/ejb/lite-remote-ejb.adoc
PR For live documentation since also merged in master
=> Fix docu around example of get-ejb-invoker-configuration

SUMMARY.adoc, documentation/payara-server/hazelcast/configuration.adoc, documentation/payara-server/hazelcast/datagrid-encryption.adoc
https://github.com/payara/Payara/pull/4433
=> PAYARA-3324 Add Data Grid Encryption Documentation

book.json, documentation/microprofile/rest-client.adoc
Updated spec references, reformatted to sentence-per-line and added few details about specifics of implementation.
=> Payara-3828: Update MP Rest Client documentation

general-info/supported-platforms.adoc
=> Update supported JVM

documentation/payara-server/request-tracing-service/configuration.adoc
Update in connection with PR https://github.com/payara/Payara/pull/4471
=> APPSERV-12 Updates description of request tracing store size property

documentation/microprofile/config.adoc
=> Fix documentation around set-config-dir asadmin command.

SUMMARY.adoc, jakartaee-certification/5.201/README.adoc, jakartaee-certification/5.201/tck-results-full-5.201.adoc
Identical to https://github.com/payara/Payara-Server-Documentation/pull/718 but just for the 5.201 branch rather than master.
=> Add TCK results for 5.201 (5.201 Branch)

documentation/microprofile/faulttolerance.adoc
Updates in connection with https://github.com/payara/Payara/pull/4534
=> APPSERV-55 Updates section on FT asadmin config

documentation/microprofile/faulttolerance.adoc
Just few minor wording corrections - changes are not actually related to changes done in APPSERV-57 but found when scanning for changes needed.
=> APPSERV-57 Minor Corrections

documentation/ecosystem/security-connectors.adoc, documentation/payara-server/public-api/oauth-support.adoc
Payara API and OAuth connector provides `OAuth2AuthenticationDefinition` annotation. There's no `@OAuth2AuthorisationMechanism` annotation
=> Use the correct OAuth annotation

documentation/payara-server/hazelcast/datagrid-encryption.adoc
=> APPSERV-39 Only sync mode normal is required

documentation/microprofile/config.adoc
In connection with https://github.com/payara/Payara/pull/4614
=> APPSERV-141 Adds section on added caching and asadmin commands to configure it

documentation/payara-server/h2/h2.adoc
=> Derby DB removed

documentation/payara-server/h2/h2.adoc
Updates already released docs for 5.201 with the change in #733
=> Derby DB removed (for 5.201 branch)

documentation/user-guides/monitoring/monitoring-console.adoc
In connection with: https://github.com/payara/monitoring-console/pull/8
=> APPSERV-146 Adds paragraph on bookmarkable URLs
