payara/Payara-Server-Documentation

- SUMMARY.md
- documentation/core-documentation/core-documentation.md
- documentation/extended-documentation/extended-documentation.md
- release-notes/release-notes.md
Without the links, generated PDF docs messed up table of contents.
Here is a preview of the gitbook: https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/3c949945cd5f0b87800a2dbe9f6b166fe6af791c/
Here is a link to download a PDF version: https://www.gitbook.com/download/pdf/book/ondrejm/payara-server-documentation-fork/v/3c949945cd5f0b87800a2dbe9f6b166fe6af791c
> Added links to top-level captions in summary

- SUMMARY.md
- documentation/payara-micro/persistent-ejb-timers.md
This is an update for 163 documentation. 
Preview here: https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/163-ejb-timers/documentation/payara-micro/persistent-ejb-timers.html
> Persistent EJB timers

- SUMMARY.md
- documentation/extended-documentation/app-deployment/deployment-descriptors.md
- documentation/extended-documentation/app-deployment/descriptor-elements.md
- documentation/extended-documentation/classloading.md
Implemented documentation on the extreme classloading isolation feature introduced on 171. Also revamped the class loading documentation with the following changes:
* Renamed the article page to **Enhanced Classloading** to denote that there are present improvements into Payara Server when talking about classloading behaviours.
* Removed the internal TOC, not needed.
* Changed and restructured the article to reflect more a technical documentation on the features. The previous style of the article was more of a set of recommendations. 
* Introduced the term **classloading delegation** to make it more consistent with the actual feature built in Payara/GlassFish.
> PYSVC-211 + Classloading documentation revamped

- documentation/extended-documentation/notification-service/notifiers/xmpp-notifier.adoc
The get-xmpp-notifier-configuration command still has room name as a column heading which will need changing. I'll make a new PR for it under the original JIRA
> Changed XMPP references to room name to room id

- documentation/extended-documentation/health-check-service/asadmin-commands.adoc
- documentation/extended-documentation/health-check-service/health-check-service.adoc
The docs are out of date - they expect that Health Check notifications go directly to the log file. In recent versions, they are routed to the Notification Service, which can send them to the log file.
> PYSVC-460 update health check svc

- book.json
Adds a plugin that turns admonition captions like WARNING or NOTE into icons, like :warning: and :information_source: 
Preview: https://ondrejm.gitbooks.io/payara-server-documentation-fork/content/v/admonition-icons/documentation/payara-micro/adding-jars.html
> Basic admonition icons

- documentation/extended-documentation/hazelcast/asadmin.adoc
- documentation/extended-documentation/hazelcast/configuration.adoc
- documentation/extended-documentation/hazelcast/enable-hazelcast.adoc
- documentation/extended-documentation/hazelcast/hazelcast.adoc
- documentation/extended-documentation/hazelcast/using-hazelcast.adoc
- documentation/extended-documentation/hazelcast/viewing-members.adoc
- documentation/extended-documentation/jmx-monitoring-service/jmx-notification-configuration.adoc
- documentation/extended-documentation/notification-service/notification-service.adoc
- documentation/user-guides/monitoring/enable-jmx-monitoring.adoc
- documentation/user-guides/monitoring/mbeans.adoc
Fixes for multiple pending changes needed to finish the #273 PR
Changes made:
* Added missing reference anchors for Hazelcast, JMS Monitoring and Monitoring Guide articles.
* Removed version disclaimer from multiple image alt texts.
* Fixed broken tables in the Hazelcast section
* Improved format for MBean reference documentation. Changed link to outdated GlassFish documentation.
> Fixes for multiple articles in preparation for 174 doc release

- SUMMARY.adoc
- book.json
- documentation/microprofile/README.adoc
- documentation/microprofile/config.adoc
- documentation/microprofile/faulttolerance.adoc
- documentation/microprofile/healthcheck.adoc
Added version info for each API page.
Using variables to specify version and URL for the current version of each MP API implemented by Payara. Makes it easy to update all in one place later.
A preview: https://docs.payara.fish/v/181-MP-fixes/documentation/microprofile/
> MP version and URL variables

- general-info/supported-platforms.adoc
It's still missing oldest supported versions for IBM SDK and AIX, please comment if you know which versions we support them since.
> Add support for IBM JDK and AIX

- documentation/payara-server/health-check-service/asadmin-commands.adoc
- documentation/payara-server/health-check-service/asadmin-commands.html
This adds the documentation changes for https://github.com/payara/Payara/pull/3663 and https://github.com/payara/Payara/pull/3679.
I used AsciidocFX to edit sources and generate the updated HTML.
In general 3 seconds on 3 new commands were added. These are meant to replace several commands in the future that I marked deprecated for now. I used the `INFO` tag for that at the very beginning of the deprecated commands as I found it used elsewhere in the documentation.
The difference to the replaced commands often is marginal. I did this slowly and careful so hopefully this pays off and I got the details correct and did not mix it up. The examples given are based on the examples given for the replaced commands and were adopted to the new commands. For the new commands I also documented some …
> PAYARA-3462 added section on new health check asadmin commands

- documentation/payara-micro/appendices/cmd-line-opts.adoc
Addresses the additional allowed time unit names for the `--requesttracingadaptivesamplingtimeunit` option (see https://github.com/payara/Payara/pull/3713).
As the options for the request tracing adaptive sampling were blank in the table I also added a description and default based on the information found in `documentation/payara-server/request-tracing-service/asadmin-commands.adoc`.
> PAYARA-3542 Added rows on request tracing adaptive sampling cmd line options

- documentation/ecosystem/netbeans-plugin/README.adoc
Removed **NetBeans + Payara plugins Bundle** section as Apache NetBeans IDE 11.0 released with Enterprises modules so complete bundle distribution not needed anymore.
> NP-23 Release Payara NetBeans IDE plugin version 1.7

- documentation/user-guides/upgrade-payara.adoc
PAYARA-3817 JDK 11 cc @rdebusscher 
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
> PAYARA-3817 Added upgrade instructions for JDK 11 domains

- documentation/payara-server/production-ready-domain.adoc
- release-notes/release-notes-192.adoc
We've agreed that removing the sys props for JDK 8 was a mistake and it's a bug that will be fixed. See PAYARA-3931.
Reverting #539.
A follow-up for #540 with updates.
After merging, don't forget:
:exclamation: This should be also merged to the master branch.
:exclamation: This should be also propagated to other copies of release notes.
> Revert ext 5.192 (updated)

- documentation/payara-server/server-configuration/jvm-options.adoc
Small docs update to show the need for jvm options to be in quotations when using the create-jvm-options asadmin command
> [PAYARA-3891] - Updated JVM options docs

- book.json
Because gitbook is quirky, it doesn't show some versions. We have problems to force it to update the versions so we link to exact commit for each version which seems to work.
> Update links to some broken versions

- jakartaee-certification/5.193/tck-results-full-5.193.1.adoc
The provided sha256sum was incorrect, likely referring to previous artifact version.
> Fix incorrect beanvalidation tck sum

- documentation/microprofile/openapi.adoc
OpenAPI command allows CORS headers since 5.192, so this has been
documented.
> PAYARA-4233 Document CORS headers

- documentation/payara-server/advanced-jdbc/advanced-connection-pool-properties.adoc
There should be empty values instead, as they were in the original markdown document: https://github.com/payara/Payara-Server-Documentation/blob/ccef1099308ad17789641b0293ca84596e187d73/documentation/extended-documentation/advanced-jdbc/advanced-connection-pool-properties.md. This probably happened during automatic transformation to Asciidoc.
> Removed multiblock comments

- documentation/microprofile/opentracing.adoc
Documentation used to state that the default library jar should be added as a library to Payara in order to use an alternate OpenTracing implementation however doing so causes ClassDefNotFoundErrors - it is required that you use the jar-with-dependencies file from a maven build to deploy as a library
> [PAYARA-3263] - Corrected minor documentation issue

- documentation/payara-server/ejb/lite-remote-ejb.adoc
Clarifications were done on how to correctly call secured remote EJBs when using the `ejb-invoker` exposed by the Lite EJB client dependency.
> Improvements for Lite Remote EJB Client Code

- documentation/payara-server/server-configuration/http/protocols.adoc
- documentation/payara-server/system-properties.adoc
This has already been merged into the Master branch. https://github.com/payara/Payara-Server-Documentation/pull/679
> CUSTCOM-18 Add TLS 1.3 support when using Zulu JDK 8 [5.194]

- documentation/payara-server/health-check-service/asadmin-commands.adoc
Documentation changes for https://github.com/payara/Payara/pull/4465.
Funnily enough the restrictions made in that PR were already anticipated by most of the documentation so that only a small change was needed.
> APPSERV-43 Removes now illegal time units from stuck thread configuration

- SUMMARY.adoc
- documentation/payara-micro/adding-jars.adoc
- documentation/payara-micro/appendices/cmd-line-opts.adoc
- documentation/payara-micro/asadmin/pre-and-post-boot-scripts.adoc
- documentation/payara-micro/configuring/config-cmd-line.adoc
- documentation/payara-micro/deploying/deploy-cmd-line.adoc
- documentation/payara-micro/rootdir.adoc
- documentation/payara-micro/starting-instance.adoc
- documentation/payara-micro/stopping-instance.adoc
I ended up documented consequences of reusing root directory much more than the new switches `--outputlauncher` and `--warmup`.
> CLOUD-41: Documentation on new switches and reuse of root directory
